module.exports = {
  onGod: "true",
  noCap: "true",
  cap: "false",
  ghosted: "return null",
  lowkey: "console",
  stan: "log",
  sus: "warn",
  crowed: "debug",
  cringe: "error",
  tea: "info",
  L: "Error",
  fr: "assert",
  grab: "require",
  ship: "exports",
  itsGiving: "return",
  drop: "return",
  dis: "this",
  outOfPocket: "Infinity",
  PERIODT: "break",
  period: "break",
  skrt: "break",
  based: "toLowerCase",
  goated: "toUpperCase",
  finna: "confirm",
  SeveralSeats: "Array",
  take: "fill"
};
