module.exports = {
  onGod: "true",
  noCap: "true",
  cap: "false",
  ghosted: "return null",
  lowkey: "console",
  stan: "log",
  sus: "warn",
  cringe: "error",
  L: "Error",
  fr: "assert",
  grab: "require",
  ship: "exports",
  itsGiving: "return",
  drop: "return",
  dis: "this",
  outOfPocket: "Infinity",
  PERIODT: "break",
  skrt: "break",
  based: "toLowerCase",
};
